--- #The MEAN Stack file
- hosts: nodes
  remote_user: ansible
  become: yes
  become_method: sudo
  vars: 
    var_node: /tmp
  tasks:
    # Install Prerequisites
    - include: tasks/prerequisites.yaml color=green
    # Install MongoDB
    - include: tasks/mongodb.yaml color=yellow
    # Install Node.js
    - include: tasks/nodejs.yaml color=blue

