# The Mongodb Playbook
- name: MongoDB | Import Public keys
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA312927

- name: MongoDB | Add Repository
  apt_repository:
    filename: '/etc/apt/sources.list.d/mongodb-org'
    repo: "deb http://repo.mongodb.org/apt/ubuntu trusty64/mongodb-org/3.2 multiverse"
    state: present
    update_cache: yes

- name: MongoDB | Install MongoDB
  apt: 
    name: mongodb-server
    state: present
    update_cache: yes

- name: MongoDB | Running State
  service:
    name: mongo
    state: started
